############################################
# propeties
# since 2006/11/10
############################################

# application name
APP_NM=HNAW

# CookieLoadBlance setting file path
ACTUAL_IP_FILE=/prod/cont-data/IP_ADDR.txt

# 0:don't read 1:read
READ_IP_FILE_SW=0

# Shift_JIS or EUC-JP or Windows-31J
CHAR_SET=Windows-31J

# Shift_JIS or EUC-JP or Windows-31J
DWNLD_CSV_CHAR_SET=Windows-31J

# CSV File Upload Encording
UPLOAD_ENCORDING=Windows-31J

# 1:iAS(JNDI) 2:Tomcat(Direct) 3:J2SDKEE(JNDI)
# 4:weblogic(JNDI) 5:OracleiAS(JNDI)
# 6:Tomcat5(JNDI)  7:OracleiAS(Direct)
CON_SW=2

# 0:practical use 1:DEBUG
DEBUG_SW=1

# 0:from System 1:from DB
CNTRL_DT_FRM_DB=1

# 0:don't use 1:use
USE_FOR_UPDATE=1

# 0:don't output 1:output message box
PERFORMANCE_SW=0

# 0:don't output 1:output message box
SESSION_ID_SW=0

# 0:don't use encodeRedirectURL 1:use encodeRedirectURL
ENCD_REDIRECT_SW=0

# 0:don't output console 1:output console
COOKIE_SW=0

# 0:don't cookie load balancing 1:do cookie load balancing
COOKIE_LOADB_SW=0

# 0:don't output 1:output message box
SNOOP_SW=0

# 0:don't call setMaxInactiveInterval 1:call setMaxInactiveInterval
SESSION_TIME_SW=0

# session-timeout time for setMaxInactiveInterval
SESSION_TIMEOUT=7200

# max maintain detail number
DTL_MAX=100

# max detail number displayed at a time
DTL_MAX_DSP_AT_A_TM=15

# min date
MIN_DATE=19000101

# max date
MAX_DATE=29991231

# smtp host
SMTP_HOST=localhost

# 0:don't service time check 1:do service time check
TIME_SW=0

# 0:don't put LF to SQL 1:put LF to SQL
SQL_LF_SW=1


# DB

# JNDI Name
JNDI_NAME=jdbc/HNAW_ORACLE001

# MS-Access
# THIN_DRIVER_URL=jdbc:odbc:TEST
# development use DB
# THIN_DRIVER_URL=jdbc:oracle:thin:@10.173.110.9:1521:LT1A
# test use DB
# THIN_DRIVER_URL=jdbc:oracle:thin:@10.64.8.29:1521:LE6A
# practical use DB
# THIN_DRIVER_URL=jdbc:oracle:thin:@10.64.8.31:1521:LE7A
THIN_DRIVER_URL=jdbc:oracle:thin:@10.173.110.9:1521:LT1A?jdDriver=oracle.jdbc.driver.OracleDriver&jdOutType=1&jdPrefix=[* DEBUG *]#SQL# 
#THIN_DRIVER_URL=jdbc:oracle:thin:@10.70.240.24:1521:LEWP7T01?jdDriver=oracle.jdbc.driver.OracleDriver&jdOutType=1&jdPrefix=[* DEBUG *]#SQL# 
#THIN_DRIVER_URL=jdbc:odbc:TEST

# MS-Access DRIVER_NAME=sun.jdbc.odbc.JdbcOdbcDriver
#DRIVER_NAME=oracle.jdbc.driver.OracleDriver
DRIVER_NAME=jp.co.powerbeans.jdbcdebug.sql.Driver
#DRIVER_NAME=sun.jdbc.odbc.JdbcOdbcDriver

DB_USER=OHN001
DB_PASS=OHN001
#DB_USER=OHN002
#DB_PASS=OHN002

# usually not use
# development use DB(MS-Access)
MS_DRIVER_URL=sun.jdbc.odbc.JdbcOdbcDriver
MS_DRIVER_NAME=jdbc:odbc:TEST
MS_USER=
MS_PASS=
